// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAOt7PZOMD-IvoXOliI8XQZTVo13O1xK94',
    appId: '1:1035319788879:web:075b1a6b38f04ec12f313a',
    messagingSenderId: '1035319788879',
    projectId: 'daevis-dbe2f',
    authDomain: 'daevis-dbe2f.firebaseapp.com',
    storageBucket: 'daevis-dbe2f.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBdjPiw72Hmp909o0MD3rlIpoOhvs-Q2DY',
    appId: '1:1035319788879:android:863cbd91feb60c012f313a',
    messagingSenderId: '1035319788879',
    projectId: 'daevis-dbe2f',
    storageBucket: 'daevis-dbe2f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDevaI0rXPzFotSoUtQb6aIHjj4C-Jroaw',
    appId: '1:1035319788879:ios:2fe40e700740d4f52f313a',
    messagingSenderId: '1035319788879',
    projectId: 'daevis-dbe2f',
    storageBucket: 'daevis-dbe2f.firebasestorage.app',
    iosBundleId: 'com.example.daevis',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDevaI0rXPzFotSoUtQb6aIHjj4C-Jroaw',
    appId: '1:1035319788879:ios:2fe40e700740d4f52f313a',
    messagingSenderId: '1035319788879',
    projectId: 'daevis-dbe2f',
    storageBucket: 'daevis-dbe2f.firebasestorage.app',
    iosBundleId: 'com.example.daevis',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAOt7PZOMD-IvoXOliI8XQZTVo13O1xK94',
    appId: '1:1035319788879:web:698a96009d7e93372f313a',
    messagingSenderId: '1035319788879',
    projectId: 'daevis-dbe2f',
    authDomain: 'daevis-dbe2f.firebaseapp.com',
    storageBucket: 'daevis-dbe2f.firebasestorage.app',
  );

}